### ISSUE TITLE
HRESULT E_FAIL Error when configuring Sanear audio renderer in MPDN

### ISSUE THREAD

**Issue by Ryrynz** [alexmarsev/sanear#7] opened 2015-08-03 10:48 UTC
Not sure where this issue lies exactly. Try configuring Sanear through the filters menu.

Quoting Zach from MPDN.

".NET is very strict when it comes to COM object conformance. For example, XySubFilter had a bug that prevented it to be used in .NET because it forgot to tell .NET it is an XySubFilter when it's queried. A common error that gets unnoticed in unmanaged code where you can cast it to anything and it'll never fail but .NET wants to make sure you can only cast it to something that is valid, for various reasons such as making sure you never have invalid access and above all security."

GraphStudio also doesn't display a status tab, so looks to be an issue with Sanear.

**Comment by zachsaw** [comment] 2015-08-03 11:39
I tested it with GraphStudioNext, both 32- and 64-bit versions to be exact.

I doubt it has anything to do with .NET though since GraphStudioNext is coded in native C++.

**Comment by alexmarsev** [comment] 2015-08-03 11:56
Alright, I can reproduce the issue with both mpdn and graphstudionext.
Will look into what I may do wrong there.

**Comment by zachsaw** [comment] 2015-08-03 13:00
Thanks Alex! Appreciate it!

**Comment by alexmarsev** [comment] 2015-08-03 13:01
Thank _you_ for reporting it.

**Comment by zachsaw** [comment] 2015-08-03 13:08
BTW, would you allow this to be included in MPDN's installer to be used with MPDN? It has much better quality than the MPC Audio Renderer MPDN currently includes in its installation.

Oh just out of curiousity, when the player's rate changes, do you resample the audio? Or do you simply request the new sample rate from the audio endpoint?

**Comment by zachsaw** [comment] 2015-08-03 13:18
You could probably take a look at how the MPC Audio Renderer does its ISpecifyPropertyPages and IPropertyPage since it works in both GraphStudioNext and MPDN.

**Comment by alexmarsev** [comment] 2015-08-03 13:39
> BTW, would you allow this to be included in MPDN's installer to be used with MPDN? It has much better quality than the MPC Audio Renderer MPDN currently includes in its installation.

I don't mind, but would prefer if you wait for at least a couple of weeks until I receive more feedback and fix any major bugs. The project is simply not mature enough. Also other than including standalone binaries, you may be interested in embedding it like mpc-hc does - no annoying (for some) tray icon, you store settings yourself, etc

> Oh just out of curiousity, when the player's rate changes, do you resample the audio? Or do you simply request the new sample rate from the audio endpoint?

Do you mean `IMediaSeeking::SetRate`? If so - I keep the same sampling rate but apply timestretching dsp. As for what reclock audio renderer does, I plan to provide some simple public interface which video renderers could use to adjust graph clock when they need it, then resample audio depending on these adjustments. Something similar to what MediaPortal-1 audio renderer provides, but much more easier to use.

> You could probably take a look at how the MPC Audio Renderer does its ISpecifyPropertyPages and IPropertyPage since it works in both GraphStudioNext and MPDN.

Thanks. I will have a look.

**Comment by zachsaw** [comment] 2015-08-03 13:47
Fantastic!  Keep up the good work!

**Comment by zachsaw** [comment] 2015-08-03 23:21
> I don't mind, but would prefer if you wait for at least a couple of weeks until I receive more feedback and fix any major bugs. The project is simply not mature enough. Also other than including standalone binaries, you may be interested in embedding it like mpc-hc does - no annoying (for some) tray icon, you store settings yourself, etc

I actually prefer the binary standalone. Integrating it into MPDN prevents users from upgrading the filters unless they disable the internal ones which kind of defeats the purpose of having it integrated to begin with. We use MPDN Extensions (open source on GitHub) to handle filter settings - the extensions API can access all the active filters as COM objects so it's very easy to extend support for any filter.

> Do you mean IMediaSeeking::SetRate? If so - I keep the same sampling rate but apply timestretching dsp. As for what reclock audio renderer does, I plan to provide some simple public interface which video renderers could use to adjust graph clock when they need it, then resample audio depending on these adjustments. Something similar to what MediaPortal-1 audio renderer provides, but much more easier to use.

AFAIK MPAR only does timestretching. Resampling is only required if you're correcting PAL speedup - i.e. lowering pitch to compensate for the speedup when the PAL media was mastered.

As I was saying, it is easy to support any new COM interfaces with MPDN Extensions. It might be a good idea to look into testing your Pitch control interface with MPDN Extensions - this way you don't have to muck around with MPC-HC or any other player's source codes and trying to get them to compile, just to test your new interface. It's much easier with MPDN Extensions and if you get it to run under .NET which is very strict when it comes to COM interfaces, you'll almost be guaranteed that it'll run in unmanaged host as well. And MPDN in turn also gains support for your new interface.

Cheers.

**Comment by Ryrynz** [comment] 2015-08-03 23:37
Was my intention to get you to replace the mpc renderer with this when the time came Zach. The audio quality improvement was astounding. Alex how is this improvement achieved when mpc also uses WASAPI? MPC audio renderer just sounds muffled in comparison. I've been using it since release and won't use anything else. I've had the odd audio hiccup when skipping but otherwise it's working well.

**Comment by zachsaw** [comment] 2015-08-03 23:48
Yeah on some of my machines the MPC audio renderer don't work (i.e. it becomes silent) when the IMediaSeeking::SetRate is set to a value besides 1.0. IIRC MPC Audio Renderer doesn't do timestretching so it asks the audio endpoint to output at a specific rate. If the hardware doesn't support it, you won't get any output.

This may or may not be better depending on the timestretching DSP used vs the audio hardware implementation (the audio hardware may very well just change its internal clock) so I'd prefer if Sanear gives you the option (accessible via COM interface) to select timestretching or directly setting the rate on the audio endpoint.

**Comment by alexmarsev** [comment] 2015-08-04 10:32
`IMediaSeeking::SetRate()` is for users who want to watch something but spend less time, let's just leave it for that.

About sampling rate adjustments (with source rate converter), if we care about sound quality (well, I do) it can only be done below pitch JND - only up to ~0.3-0.6%. And in that public interface I was talking about above (let's call it "guided reclock" from now on) I plan to support it. And transparently to video renderer. And it's useful not only for 3:2 pulldown, but also for eliminating half-frame offset and clock drift.

**Comment by alexmarsev** [comment] 2015-08-05 10:42
Fixed, will be included in the next release.

**Closed as completed by alexmarsev** 2015-08-05 10:42 UTC
Labels: bug

**Comment by zachsaw** [comment] 2015-08-05 10:43
Fantastic!
